"""Pocket TTS 3 (English) web server.

- Loads the Pocket TTS v3 English model (lazy, in a dedicated engine thread).
- Voice cloning: decodes an uploaded audio sample, encodes a voice state,
  returns it as safetensors (base64) which the browser stores in IndexedDB.
- Streaming TTS: framed 16-bit PCM (24 kHz mono), while simultaneously
  assembling an M4A (AAC) file for download.
- Setup: validates a HuggingFace token and downloads the gated
  voice-cloning weights locally (persisted in /home/user/models).
"""

import base64
import gc
import io
import json
import os
import secrets
import queue
import re
import struct
import threading
import time
import uuid
from pathlib import Path

import numpy as np
from fastapi import FastAPI, File, Form, HTTPException, UploadFile, Request
from fastapi.responses import FileResponse, JSONResponse, Response, StreamingResponse
from fastapi.staticfiles import StaticFiles
import httpx
import torch

from pocket_tts import TTSModel, export_model_state

ROOT = Path(__file__).resolve().parent.parent
APP_DIR = ROOT / "app"
DATA_DIR = Path(os.environ.get("POCKET_DATA_DIR", str(ROOT / "data")))
MODELS_DIR = DATA_DIR / "models"
OUT_DIR = DATA_DIR / "out"
MODELS_DIR.mkdir(parents=True, exist_ok=True)
OUT_DIR.mkdir(parents=True, exist_ok=True)
ACCESS_KEY = os.environ.get("APP_ACCESS_KEY", "")
if os.environ.get("RAILWAY_SERVICE_ID") and not ACCESS_KEY:
    raise RuntimeError("APP_ACCESS_KEY must be configured before hosting this app")
torch.set_num_threads(int(os.environ.get("POCKET_THREADS", "2")))
LOCAL_CONFIG = MODELS_DIR / "local_english.yaml"
READY_FLAG = MODELS_DIR / "READY"
JOBS_FILE = OUT_DIR / "jobs.json"

SR = 24000
B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"

# revisions pinned in the package's english.yaml
REV_MODEL = "39592ff23c9ef80098bb74895d104c26275fe2c9"
REV_TOK = "d29db7978e464fb90cb3359ee0c69a273b9142cc"
REV_EMB = "e81d79e8194ad4c7ce879c87a4258ef20cbf2487"

BUILTIN_VOICES = [
    ("alba", "Alba", "Warm, casual (female)"),
    ("anna", "Anna", "Clear, neutral (female)"),
    ("vera", "Vera", "Bright, even (female)"),
    ("jean", "Jean", "Calm, freeform (male)"),
    ("charles", "Charles", "Deep, steady (male)"),
    ("paul", "Paul", "Smooth, relaxed (male)"),
    ("marius", "Marius", "Easygoing (male)"),
    ("eve", "Eve", "Soft, friendly (female)"),
    ("michael", "Michael", "Steady narrator (male)"),
    ("jane", "Jane", "Neutral, balanced (female)"),
    ("mary", "Mary", "Warm, conversational (female)"),
    ("george", "George", "Round, mellow (male)"),
    ("cosette", "Cosette", "Expressive (female)"),
    ("fantine", "Fantine", "Gentle (female)"),
]
BUILTIN_IDS = {v[0] for v in BUILTIN_VOICES}

PREVIEW_TEXT = (
    "Hi there! This is a test of your new voice, generated by Pocket TTS three. "
    "If you can hear me clearly, the cloning worked."
)


# --------------------------------------------------------------------------
# text segmentation
# --------------------------------------------------------------------------

def split_text(text: str, max_chars: int = 400):
    """Split text into (segment, ends_paragraph) chunks for steady generation."""
    text = re.sub(r"[ \t]+", " ", text)
    paras = re.split(r"\n\s*\n", text)
    units = []  # (sentence, last_of_paragraph)
    for p in paras:
        p = re.sub(r"\n", " ", p).strip()
        if not p:
            continue
        ss = [s.strip() for s in re.split(r"(?<=[.!?])\s+(?=[A-Z0-9\"']|\()", p)]
        ss = [s for s in ss if s]
        if not ss:
            ss = [p[i : i + max_chars] for i in range(0, len(p), max_chars)]
        for k, s in enumerate(ss):
            units.append((s, k == len(ss) - 1))

    segs = []
    buf, buf_flag = "", False
    for s, is_last in units:
        if buf and len(buf) + len(s) + 1 > max_chars:
            segs.append((buf, buf_flag))
            buf, buf_flag = s, is_last
        else:
            buf = (buf + " " + s) if buf else s
            buf_flag = is_last
        while len(buf) > max_chars + 150:
            cut = buf.rfind(" ", 0, max_chars)
            if cut < 80:
                cut = max_chars
            segs.append((buf[:cut].strip(), False))
            buf, buf_flag = buf[cut + 1 :], False
    if buf.strip():
        segs.append((buf.strip(), buf_flag))
    return segs


def clean_for_tts(text: str) -> str:
    text = re.sub(r"https?://\S+|www\.\S+", " web link ", text)
    return text.strip()


# --------------------------------------------------------------------------
# audio decode / encode
# --------------------------------------------------------------------------

def decode_audio_bytes(data: bytes) -> np.ndarray:
    """Decode any common audio format to float32 mono @ SR using PyAV."""
    import av

    resampler = av.AudioResampler(format="s16", layout="mono", rate=SR)
    frames = []
    samples = 0
    with av.open(io.BytesIO(data)) as container:
        for frame in container.decode(audio=0):
            for out in resampler.resample(frame):
                frames.append(out.to_ndarray().ravel())
                samples += out.samples
            if samples >= SR * 30:
                break
    for out in resampler.resample(None):
        frames.append(out.to_ndarray().ravel())
    if not frames:
        raise ValueError("No audio found in file")
    return np.concatenate(frames)[:SR * 30].astype(np.float32) / 32768.0


class M4aWriter:
    """Progressive AAC/m4a encoder (PyAV)."""

    def __init__(self, path: Path):
        import av

        self.av = av
        self.container = av.open(str(path), "w")
        self.stream = self.container.add_stream("aac", rate=SR)
        self.stream.bit_rate = 64_000
        self.stream.layout = "mono"

    def write(self, pcm16: bytes):
        if not pcm16:
            return
        n = len(pcm16) // 2
        frame = self.av.AudioFrame(format="s16", layout="mono", samples=n)
        frame.sample_rate = SR
        frame.planes[0].update(pcm16)
        for pkt in self.stream.encode(frame):
            self.container.mux(pkt)

    def close(self):
        try:
            for pkt in self.stream.encode(None):
                self.container.mux(pkt)
        finally:
            self.container.close()


class JobCancelled(Exception):
    pass


def to_pcm16(tensor) -> bytes:
    a = tensor.detach().cpu().numpy().ravel()
    a = np.clip(a * 32767.0, -32768, 32767).astype("<i2")
    return a.tobytes()


# --------------------------------------------------------------------------
# engine (single worker thread)
# --------------------------------------------------------------------------

class Engine:
    def __init__(self):
        self.q: "queue.Queue" = queue.Queue()
        self.model = None
        self.cloning_enabled = False
        self.load_lock = threading.Lock()
        self.load_error = None
        self.loading = False
        threading.Thread(target=self._loop, daemon=True, name="engine").start()

    # -- model ----------------------------------------------------------
    def _ensure_model(self):
        with self.load_lock:
            if self.model is not None:
                return self.model
            t0 = time.time()
            if LOCAL_CONFIG.exists():
                self.model = TTSModel.load_model(config=str(LOCAL_CONFIG))
            else:
                self.model = TTSModel.load_model(language="english")
            self.cloning_enabled = bool(getattr(self.model, "has_voice_cloning", False))
            self.load_error = None
            print(f"[engine] model ready in {time.time()-t0:.1f}s cloning={self.cloning_enabled}", flush=True)
        return self.model

    def warm_up(self):
        try:
            self._ensure_model()
        except Exception as e:  # noqa: BLE001
            print(f"[engine] warm-up failed: {e}", flush=True)
            self.load_error = str(e)
        finally:
            self.loading = False

    # -- job loop ---------------------------------------------------------
    def _loop(self):
        while True:
            job = self.q.get()
            kind, payload, out = job
            try:
                getattr(self, f"_do_{kind}")(payload, out)
            except (ValueError, HTTPException) as e:  # expected client errors
                print(f"[engine] {kind} rejected: {e}", flush=True)
                out.put(("error", str(e)))
            except Exception as e:  # noqa: BLE001
                import traceback

                traceback.print_exc()
                out.put(("error", str(e)))

    def submit(self, kind, payload):
        """Blocking submit used by sync-context endpoints (engine is threaded)."""
        out: "queue.Queue" = queue.Queue()
        self.q.put((kind, payload, out))
        try:
            return out.get(timeout=600)
        except queue.Empty:
            return ("error", "The speech engine is busy. Please try again shortly.")

    # -- voice state ------------------------------------------------------
    def _voice_state(self, payload):
        model = self._ensure_model()
        if payload.get("voice_builtin"):
            name = payload["voice_builtin"]
            if name not in BUILTIN_IDS:
                raise ValueError(f"Unknown built-in voice '{name}'")
            p = MODELS_DIR / "wc" / "languages" / "english" / "embeddings" / f"{name}.safetensors"
            if not p.exists():
                from huggingface_hub import hf_hub_download

                p = Path(
                    hf_hub_download(
                        repo_id="kyutai/pocket-tts-without-voice-cloning",
                        filename=f"languages/english/embeddings/{name}.safetensors",
                        revision=REV_EMB,
                    )
                )
            return model.get_state_for_audio_prompt(str(p))
        b64 = payload.get("voice_state_b64")
        if not b64:
            raise ValueError("No voice supplied")
        tmp = OUT_DIR / f"_state_{uuid.uuid4().hex}.safetensors"
        if not isinstance(b64, str) or len(b64) > 32_000_000:
            raise ValueError("Voice file is too large.")
        tmp.write_bytes(base64.b64decode(b64, validate=True))
        try:
            return model.get_state_for_audio_prompt(str(tmp))
        finally:
            tmp.unlink(missing_ok=True)

    # -- clone ------------------------------------------------------------
    def _do_clone(self, payload, out):
        model = self._ensure_model()
        if not self.cloning_enabled:
            raise ValueError(
                "Voice cloning needs the full model. Open Setup and connect your HuggingFace token."
            )
        arr = decode_audio_bytes(payload["file_bytes"])
        dur = len(arr) / SR
        if dur < 3.0:
            raise ValueError(f"Sample is {dur:.1f}s — record at least 3 seconds (5–30s is ideal).")
        if dur > 30.0:
            arr = arr[: int(30.0 * SR)]
            dur = 30.0
        t0 = time.time()
        state = model.get_state_for_audio_prompt(torch.from_numpy(arr).unsqueeze(0))
        tmp = OUT_DIR / f"_vstate_{uuid.uuid4().hex}.safetensors"
        export_model_state(state, tmp)
        size = tmp.stat().st_size
        out.put(("ok", {
            "state_b64": base64.b64encode(tmp.read_bytes()).decode("ascii"),
            "duration_s": round(dur, 1),
            "size_mb": round(size / 1e6, 1),
            "encode_s": round(time.time() - t0, 1),
        }))
        tmp.unlink(missing_ok=True)

    # -- preview -----------------------------------------------------------
    def _do_preview(self, payload, out):
        model = self._ensure_model()
        vs = self._voice_state(payload)
        text = payload.get("text") or PREVIEW_TEXT
        audio = model.generate_audio(vs, text)
        pcm = to_pcm16(audio)
        wav = _wav_bytes(pcm, SR)
        out.put(("ok", {"wav": wav, "duration_s": round(len(pcm) / 2 / SR, 1)}))

    # -- tts prepare + stream ----------------------------------------------
    def _do_prepare_tts(self, payload, out):
        model = self._ensure_model()
        text = clean_for_tts(payload.get("text", ""))
        if len(text) < 2:
            raise ValueError("Nothing to read — enter some text or upload a file first.")
        if len(text) > 500_000:
            raise ValueError("Please generate one chapter or section at a time (up to 500,000 characters).")
        vs = self._voice_state(payload)  # validates the voice early
        segs = split_text(text)
        job_id = uuid.uuid4().hex[:12]
        job_dir = OUT_DIR / job_id
        job_dir.mkdir(parents=True, exist_ok=True)
        est_s = len(text) / 15.0
        out.put(("ok", {
            "job_id": job_id,
            "segments": len(segs),
            "chars": len(text),
            "est_seconds": int(est_s),
            "_vs": vs,
            "_segs": segs,
            "_job_dir": job_dir,
        }))

    def _do_tts(self, payload, out):
        model = self._ensure_model()
        vs = payload["_vs"]
        segs = payload["_segs"]
        job_dir: Path = payload["_job_dir"]
        job_id = payload["job_id"]
        title = (payload.get("title") or "narration")[:80]
        cancel_f = job_dir / "CANCEL"

        frames_path = job_dir / "frames.bin"
        m4a_path = job_dir / "audio.m4a"
        writer = M4aWriter(m4a_path)
        pcm_total = 0
        t0 = time.time()
        cancelled = False
        failure = None
        try:
            with open(frames_path, "wb", buffering=0) as f:
                for i, (seg, para_end) in enumerate(segs):
                    if cancel_f.exists():
                        raise JobCancelled()
                    for chunk in model.generate_audio_stream(vs, seg, copy_state=True):
                        if cancel_f.exists():
                            raise JobCancelled()
                        pcm = to_pcm16(chunk)
                        f.write(struct.pack("<I", len(pcm)) + pcm)
                        writer.write(pcm)
                        pcm_total += len(pcm)
                    gap = 0.5 if para_end else 0.25
                    gap_pcm = b"\x00\x00" * int(SR * gap)
                    f.write(struct.pack("<I", len(gap_pcm)) + gap_pcm)
                    writer.write(gap_pcm)
                    pcm_total += len(gap_pcm)
                    if i % 5 == 4:
                        print(f"[tts {job_id}] seg {i+1}/{len(segs)} {time.time()-t0:.0f}s", flush=True)
        except JobCancelled:
            print(f"[tts {job_id}] cancelled after {time.time()-t0:.0f}s", flush=True)
            cancelled = True
        except Exception as e:  # noqa: BLE001
            print(f"[tts {job_id}] failed: {e}", flush=True)
            failure = str(e)
        finally:
            writer.close()
        if cancelled:
            frames_path.unlink(missing_ok=True)
            m4a_path.unlink(missing_ok=True)
            out.put(("done", {"cancelled": True}))
            return
        if failure:
            (job_dir / "FAIL").write_text(failure)
            out.put(("error", failure))
            return
        (job_dir / "DONE").touch()
        meta = {
            "id": job_id,
            "title": title,
            "voice": payload.get("voice_label", "voice"),
            "created": int(time.time()),
            "duration_s": round(pcm_total / 2 / SR, 1),
            "chars": payload.get("chars", 0),
        }
        _save_job(meta)
        out.put(("done", meta))

    # -- setup (gated model) ------------------------------------------------
    def _do_setup(self, payload, out):
        token = payload["token"]
        from huggingface_hub import hf_hub_download

        t0 = time.time()
        files = {
            "ptt/languages/english/model.safetensors": (
                "kyutai/pocket-tts", "languages/english/model.safetensors", REV_MODEL, True),
            "wc/languages/english/tokenizer.model": (
                "kyutai/pocket-tts-without-voice-cloning", "languages/english/tokenizer.model", REV_TOK, False),
        }
        for name in BUILTIN_IDS:
            files[f"wc/languages/english/embeddings/{name}.safetensors"] = (
                "kyutai/pocket-tts-without-voice-cloning",
                f"languages/english/embeddings/{name}.safetensors", REV_EMB, False,
            )
        for rel, (repo, fname, rev, gated) in files.items():
            dest = MODELS_DIR / rel
            if dest.exists() and dest.stat().st_size > 0:
                continue
            dest.parent.mkdir(parents=True, exist_ok=True)
            hf_hub_download(
                repo_id=repo,
                filename=fname,
                revision=rev,
                token=token if gated else None,
                local_dir=str(MODELS_DIR / rel.split("/")[0]),
            )
        # local config: package english.yaml with local paths
        from pocket_tts.utils.config import CONFIGS_DIR

        src = (CONFIGS_DIR / "english.yaml").read_text()
        src = re.sub(
            r"^weights_path:.*$",
            f"weights_path: {MODELS_DIR}/ptt/languages/english/model.safetensors",
            src,
            flags=re.M,
        )
        src = re.sub(
            r"^(\s*)tokenizer_path:.*$",
            rf"\1tokenizer_path: {MODELS_DIR}/wc/languages/english/tokenizer.model",
            src,
            flags=re.M,
        )
        LOCAL_CONFIG.write_text(src)

        # reload model with the local (voice-cloning) weights
        with self.load_lock:
            if self.model is not None:
                del self.model
                self.model = None
            gc.collect()
            self.model = TTSModel.load_model(config=str(LOCAL_CONFIG))
            self.cloning_enabled = bool(getattr(self.model, "has_voice_cloning", False))
            if not self.cloning_enabled:
                raise ValueError("The full voice-cloning model could not be loaded.")
            self.load_error = None
            READY_FLAG.write_text(f"ok {time.time()}\n")
        print(f"[setup] done in {time.time()-t0:.0f}s cloning={self.cloning_enabled}", flush=True)
        out.put(("ok", {"cloning_enabled": self.cloning_enabled, "seconds": round(time.time() - t0)}))


def _wav_bytes(pcm16: bytes, sr: int) -> bytes:
    h = io.BytesIO()
    h.write(b"RIFF")
    h.write(struct.pack("<I", 36 + len(pcm16)))
    h.write(b"WAVEfmt ")
    h.write(struct.pack("<IHHIIHH", 16, 1, 1, sr, sr * 2, 2, 16))
    h.write(b"data")
    h.write(struct.pack("<I", len(pcm16)))
    h.write(pcm16)
    return h.getvalue()


def _jobs():
    if JOBS_FILE.exists():
        try:
            return json.loads(JOBS_FILE.read_text())
        except Exception:  # noqa: BLE001
            return []
    return []


def _save_job(meta):
    jobs = _jobs()
    jobs = [j for j in jobs if j["id"] != meta["id"]]
    jobs.insert(0, meta)
    old_jobs = jobs[6:]
    jobs = jobs[:6]
    JOBS_FILE.write_text(json.dumps(jobs, indent=1))
    # prune finished-but-old job dirs only (never touch in-flight jobs)
    keep = {j["id"] for j in jobs[:6]}
    for j in old_jobs:
        d = OUT_DIR / j["id"]
        if d.is_dir():
            import shutil

            shutil.rmtree(d, ignore_errors=True)


engine = Engine()
app = FastAPI(title="Pocket TTS 3 (English)")


@app.middleware("http")
async def protect_app(request: Request, call_next):
    if request.url.path != "/health" and ACCESS_KEY:
        supplied = request.headers.get("x-pocket-key", "")
        if not secrets.compare_digest(supplied, ACCESS_KEY):
            return JSONResponse({"detail": "Open Pocket TTS using your private app link."}, status_code=401)
    response = await call_next(request)
    response.headers["X-Content-Type-Options"] = "nosniff"
    if request.url.path.startswith("/api/"):
        response.headers["Cache-Control"] = "no-store"
    return response


@app.get("/health")
def health():
    return {"ok": True}


# --------------------------------------------------------------------------
# API
# --------------------------------------------------------------------------

@app.get("/api/status")
def status():
    ready = engine.model is not None
    cloning = engine.cloning_enabled
    if not ready and not engine.loading:
        engine.loading = True
        threading.Thread(target=engine.warm_up, daemon=True).start()
    return {
        "ready": ready,
        "cloning_enabled": cloning,
        "ready_flag": cloning or READY_FLAG.exists(),
        "voices": [{"id": f"builtin:{i}", "name": n, "desc": d} for i, n, d in BUILTIN_VOICES],
        "engine": "pocket-tts 3.1.0 · english",
        "error": engine.load_error,
    }


@app.post("/api/setup")
def setup(body: dict):
    token = (body.get("token") or "").strip()
    if not token:
        raise HTTPException(400, "Missing token")
    try:
        r = httpx.get(
            "https://huggingface.co/api/whoami",
            headers={"Authorization": f"Bearer {token}"},
            timeout=20,
        )
    except Exception as e:  # noqa: BLE001
        raise HTTPException(502, f"Could not reach HuggingFace: {e}")
    if r.status_code != 200:
        raise HTTPException(401, "That token was rejected by HuggingFace.")
    user = r.json().get("name", "user")
    ok, res = engine.submit("setup", {"token": token})
    if ok != "ok":
        raise HTTPException(500, f"Setup failed: {res}")
    return {"ok": True, "hf_user": user, **res}


@app.post("/api/clone")
async def clone(file: UploadFile = File(...), name: str = Form("My voice")):
    data = await file.read(40_000_001)
    if len(data) < 8_000:
        raise HTTPException(400, "File is too small to be an audio sample.")
    if len(data) > 40_000_000:
        raise HTTPException(400, "File too large (max 40 MB).")
    ok, res = await _engine_submit("clone", {"file_bytes": data, "name": name})
    if ok != "ok":
        raise HTTPException(422, res)
    return res


@app.post("/api/preview")
async def preview(body: dict):
    if len(body.get("text", "")) > 1000:
        raise HTTPException(400, "Preview text is too long.")
    ok, res = await _engine_submit("preview", body)
    if ok != "ok":
        raise HTTPException(422, res)
    return Response(res["wav"], media_type="audio/wav",
                    headers={"X-Duration": str(res["duration_s"])})


@app.post("/api/tts")
async def tts(body: dict):
    ok, res = await _engine_submit("prepare_tts", body)
    if ok != "ok":
        raise HTTPException(422, res)
    job_id = res["job_id"]
    meta = {
        "job_id": job_id,
        "_vs": res["_vs"],
        "_segs": res["_segs"],
        "_job_dir": res["_job_dir"],
        "chars": res["chars"],
        "voice_label": body.get("voice_label", "voice"),
        "title": body.get("title", "narration"),
    }
    # fire the (long-running) generation on the engine thread
    engine.q.put(("tts", meta, queue.Queue()))

    job_dir = OUT_DIR / job_id
    frames = job_dir / "frames.bin"
    done_f = job_dir / "DONE"
    cancel_f = job_dir / "CANCEL"
    fail_f = job_dir / "FAIL"

    async def stream():
        import asyncio

        off = 0
        while True:
            try:
                size = frames.stat().st_size
            except FileNotFoundError:
                size = 0
            if off < size:
                with open(frames, "rb") as f:
                    f.seek(off)
                    data = f.read(min(1 << 20, size - off))
                off += len(data)
                yield data
                continue
            if done_f.exists() or cancel_f.exists() or fail_f.exists():
                break
            await asyncio.sleep(0.15)

    return StreamingResponse(
        stream(),
        media_type="application/octet-stream",
        headers={
            "X-Job-Id": job_id,
            "X-Sample-Rate": str(SR),
            "X-Segments": str(res["segments"]),
            "X-Est-Seconds": str(res["est_seconds"]),
            "Cache-Control": "no-store",
        },
    )


@app.post("/api/jobs/{job_id}/cancel")
def cancel_job(job_id: str):
    if not re.fullmatch(r"[a-f0-9]{12}", job_id):
        raise HTTPException(404, "Job not found")
    d = OUT_DIR / job_id
    if d.exists():
        (d / "CANCEL").touch()
    return {"ok": True}


@app.get("/api/jobs/{job_id}")
def job_status(job_id: str):
    if not re.fullmatch(r"[a-f0-9]{12}", job_id):
        raise HTTPException(404, "Job not found")
    d = OUT_DIR / job_id
    if not d.exists():
        raise HTTPException(404, "Job not found")
    if (d / "FAIL").exists():
        return {"status": "failed", "error": (d / "FAIL").read_text()}
    if (d / "CANCEL").exists():
        return {"status": "cancelled"}
    return {"status": "done" if (d / "DONE").exists() else "generating"}


@app.get("/api/jobs")
def jobs():
    return {"jobs": _jobs()[:12]}


@app.get("/api/download/{job_id}")
def download(job_id: str):
    if not re.fullmatch(r"[a-f0-9]{12}", job_id):
        raise HTTPException(404, "Job not found")
    p = OUT_DIR / job_id / "audio.m4a"
    if not p.exists() or not (p.parent / "DONE").exists():
        raise HTTPException(404, "Not found (the file may have been pruned).")
    meta = next((j for j in _jobs() if j["id"] == job_id), None)
    title = re.sub(r"[^A-Za-z0-9 _\-]", "", (meta or {}).get("title", "narration")).strip() or "narration"
    return FileResponse(p, media_type="audio/mp4", filename=f"{title[:60]}.m4a")


async def _engine_submit(kind, payload):
    import asyncio

    def run():
        return engine.submit(kind, payload)

    return await asyncio.to_thread(run)


# static frontend (last so /api/* wins)
app.mount("/", StaticFiles(directory=str(APP_DIR), html=True), name="app")
